### ISSUE TITLE
%active_site% is not returning within Slack

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/edd-slack#95]
As per this ticket (https://secure.helpscout.net/conversation/518526689/75547?folderId=180504), there appears to be the following issue with the Slack extension:

The license activation %active_site% text replacement does not appear be working. The customer validated that the site is recorded within the EDD SL license details, though its not resolving within the Slack notification.

I spoke to @sunnyratilal and he mentioned the following:

```
It seems to be that the URL isn’t correctly being passed

It’s only an issue when posting `deactivate_license` messages to Slack, I believe
```

**Comment by d4mation** [comment]
They are likely using `EDD_License` rather than following the Samples in EDD Software Licensing. The Samples pass through `url` as one of their API Params.

For Themes:
https://github.com/easydigitaldownloads/EDD-Software-Licensing/blob/3396d16d89d87665eb7fe0223efba7bf25d8d8f8/samples/edd-sample-theme/updater/theme-updater-admin.php#L256-L271

For Plugins:
https://github.com/easydigitaldownloads/EDD-Software-Licensing/blob/ae0a47c5302e63830c11f81cbe8d461b4fb0845a/samples/edd-sample-plugin/edd-sample-plugin.php#L120-L144

If the `EDD_License` Class were updated to either include `'url' => home_url()` in its own Activate and Deactivate methods or otherwise allowed its API Parameters to be Filtered, this could be solved using the `EDD_License` Class.
